name: Integration Tests

on:
  push:
    branches: [master]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Run Integration tests 🧪
        run: |
          yarn install
          yarn e2e:ci
